### ISSUE TITLE
scheme type definitions use type name inappropriately

### ISSUE THREAD

**Issue by rogpeppe** [mhemmings/openapi-httprequest#8]
Given this OpenAPI spec
```
    ErrorCode:
      type: string
      description: |-
        A code representing the kind of error.
        TODO enumerate all the possible error codes here?
    Error:
      type: object
      properties:
        code:
          $ref: "#/components/schemas/ErrorCode"
```

The following code is generated:
```
type Error struct {
	ErrorCode string `json:"code"`
}

type ErrorCode string
```

The field name of the Error struct should probably be `Code` not `ErrorCode`,
and its type should be `ErrorCode` not string.

**Comment by mhemmings** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openapi-httprequest: scheme type definitions use type name inappropriately](https://trello.com/c/YKNKH5sv/1178-openapi-httprequest-scheme-type-definitions-use-type-name-inappropriately)
